default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV["CI"]
    setup_ci if ENV["CI"]
    sh("git config user.name 'CI Bot'")
    sh("git config user.email 'ci-bot@dangerndiffer.com'")
  end

  desc "Auth to App Store Connect"
  private_lane :asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "asc_api_key.p8",
      in_house: false
    )
  end

  private_lane :setup_signing do |options|
    match(type: "appstore", readonly: true, api_key: options[:api_key])

    # 2. Ambil path profile yang diunduh match
    # Ini akan mencari file .mobileprovision terbaru di folder profil
    # profile_path = Dir["#{Dir.home}/Library/Developer/Xcode/UserData/Provisioning Profiles/*.mobileprovision"].max_by { |f| File.mtime(f) }

    # 3. Paksa gunakan profile tersebut ke target
    # update_project_provisioning(
    #   xcodeproj: "WorkspacyAR.xcodeproj",
    #   target_filter: "WorkspacyAR",
    #   profile: profile_path
    # )
  end

  desc "Push to dev branch -> patch bump + TestFlight"
  lane :dev_patch do
    api_key = asc_api_key
    setup_signing(api_key: api_key)

    current = get_version_number(target: "WorkspacyAR")
    major, minor, patch = current.split(".").map(&:to_i)
    new_version = "#{major}.#{minor}.#{patch + 1}"
    increment_version_number(version_number: new_version)
    increment_build_number(build_number: ENV["GITHUB_RUN_NUMBER"])

    build_app(
      scheme: "WorkspacyAR",
      clean: true,
      export_method: "app-store",
      output_directory: "./build",
      export_team_id: "CWXJ4ZG5J4",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: {
            "com.dangerndiffer.WorkspacyAR" => ENV["sigh_com.dangerndiffer.WorkspacyAR_appstore_profile-name"]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

    git_commit(
      path: ["*.xcodeproj/project.pbxproj"],
      message: "chore(ci): bump version to #{new_version} (#{ENV['GITHUB_RUN_NUMBER']}) [skip ci]"
    )
    push_to_git_remote(remote_branch: "dev")
  end

  desc "GitHub Release published in main -> set version from tag + TestFlight"
  lane :release do
    api_key = asc_api_key
    setup_signing(api_key: api_key)

    version = ENV["RELEASE_TAG"].sub(/^v/, "")
    increment_version_number(version_number: version)
    increment_build_number(build_number: ENV["GITHUB_RUN_NUMBER"])

    build_app(
      scheme: "WorkspacyAR",
      export_method: "app-store",
      output_directory: "./build"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

    git_commit(
      path: ["*.xcodeproj/project.pbxproj"],
      message: "chore(release): version #{version} (#{ENV['GITHUB_RUN_NUMBER']}) [skip ci]"
    )
    push_to_git_remote(remote_branch: "main")
  end
end
